name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Generate Snake
        run: node index.js

      - name: Commit and push
        run: |
          git config --global user.email "adslucasprog@gmail.com"
          git config --global user.name "lucasmasternoob"
          git add .
          git commit -m "Add snake animation"
          git push
